[package]
name = "wot-replays-cli"
version = "0.1.0"
authors = ["Sergey Tsaplin <me@sergeytsaplin.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
wot-replays = {path = "../wot-replays-lib"}